title: Robert Watts # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Junior Developer, Proficient in Python, Machine Learning and related technologies. Hold further experience in SQL, with light interaction with HTML, js and CSS.
  <br><br>
  Professional experience: 6 years within Investment Banking Finance. Fully Qualified CIMA Accountant.
  <br><br>
  <a href="https://www.linkedin.com/in/robertawatts/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
